//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tron.DebugClient.ClientService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseReq", Namespace="http://schemas.datacontract.org/2004/07/Tron.WebService.TransportClasses")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Tron.DebugClient.ClientService.CompleteLoginReq))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Tron.DebugClient.ClientService.CreatePlayerReq))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Tron.DebugClient.ClientService.WaitGameStartReq))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Tron.DebugClient.ClientService.GetPlayerViewReq))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Tron.DebugClient.ClientService.PerformMoveReq))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Tron.DebugClient.ClientService.WaitNextTurnReq))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Tron.DebugClient.ClientService.GetTurnResultReq))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Tron.DebugClient.ClientService.LeaveGameReq))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Tron.DebugClient.ClientService.InitLoginReq))]
    public partial class BaseReq : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Tron.DebugClient.ClientService.ReqAuth AuthField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Tron.DebugClient.ClientService.ReqAuth Auth {
            get {
                return this.AuthField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthField, value) != true)) {
                    this.AuthField = value;
                    this.RaisePropertyChanged("Auth");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReqAuth", Namespace="http://schemas.datacontract.org/2004/07/Tron.WebService.TransportClasses")]
    [System.SerializableAttribute()]
    public partial class ReqAuth : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SequenceNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SessionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TeamNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthCode {
            get {
                return this.AuthCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthCodeField, value) != true)) {
                    this.AuthCodeField = value;
                    this.RaisePropertyChanged("AuthCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientName {
            get {
                return this.ClientNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientNameField, value) != true)) {
                    this.ClientNameField = value;
                    this.RaisePropertyChanged("ClientName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SequenceNumber {
            get {
                return this.SequenceNumberField;
            }
            set {
                if ((this.SequenceNumberField.Equals(value) != true)) {
                    this.SequenceNumberField = value;
                    this.RaisePropertyChanged("SequenceNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SessionId {
            get {
                return this.SessionIdField;
            }
            set {
                if ((this.SessionIdField.Equals(value) != true)) {
                    this.SessionIdField = value;
                    this.RaisePropertyChanged("SessionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TeamName {
            get {
                return this.TeamNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TeamNameField, value) != true)) {
                    this.TeamNameField = value;
                    this.RaisePropertyChanged("TeamName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompleteLoginReq", Namespace="http://schemas.datacontract.org/2004/07/Tron.WebService.TransportClasses")]
    [System.SerializableAttribute()]
    public partial class CompleteLoginReq : Tron.DebugClient.ClientService.BaseReq {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChallengeResponseField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChallengeResponse {
            get {
                return this.ChallengeResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.ChallengeResponseField, value) != true)) {
                    this.ChallengeResponseField = value;
                    this.RaisePropertyChanged("ChallengeResponse");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreatePlayerReq", Namespace="http://schemas.datacontract.org/2004/07/Tron.WebService.TransportClasses")]
    [System.SerializableAttribute()]
    public partial class CreatePlayerReq : Tron.DebugClient.ClientService.BaseReq {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WaitGameStartReq", Namespace="http://schemas.datacontract.org/2004/07/Tron.WebService.TransportClasses")]
    [System.SerializableAttribute()]
    public partial class WaitGameStartReq : Tron.DebugClient.ClientService.BaseReq {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PlayerIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlayerId {
            get {
                return this.PlayerIdField;
            }
            set {
                if ((this.PlayerIdField.Equals(value) != true)) {
                    this.PlayerIdField = value;
                    this.RaisePropertyChanged("PlayerId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPlayerViewReq", Namespace="http://schemas.datacontract.org/2004/07/Tron.WebService.TransportClasses")]
    [System.SerializableAttribute()]
    public partial class GetPlayerViewReq : Tron.DebugClient.ClientService.BaseReq {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PlayerIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlayerId {
            get {
                return this.PlayerIdField;
            }
            set {
                if ((this.PlayerIdField.Equals(value) != true)) {
                    this.PlayerIdField = value;
                    this.RaisePropertyChanged("PlayerId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PerformMoveReq", Namespace="http://schemas.datacontract.org/2004/07/Tron.WebService.TransportClasses")]
    [System.SerializableAttribute()]
    public partial class PerformMoveReq : Tron.DebugClient.ClientService.BaseReq {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PlayerIdField;
        
        private Tron.DebugClient.ClientService.EnPoint PositionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlayerId {
            get {
                return this.PlayerIdField;
            }
            set {
                if ((this.PlayerIdField.Equals(value) != true)) {
                    this.PlayerIdField = value;
                    this.RaisePropertyChanged("PlayerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Tron.DebugClient.ClientService.EnPoint Position {
            get {
                return this.PositionField;
            }
            set {
                if ((object.ReferenceEquals(this.PositionField, value) != true)) {
                    this.PositionField = value;
                    this.RaisePropertyChanged("Position");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WaitNextTurnReq", Namespace="http://schemas.datacontract.org/2004/07/Tron.WebService.TransportClasses")]
    [System.SerializableAttribute()]
    public partial class WaitNextTurnReq : Tron.DebugClient.ClientService.BaseReq {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PlayerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RefTurnField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlayerId {
            get {
                return this.PlayerIdField;
            }
            set {
                if ((this.PlayerIdField.Equals(value) != true)) {
                    this.PlayerIdField = value;
                    this.RaisePropertyChanged("PlayerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RefTurn {
            get {
                return this.RefTurnField;
            }
            set {
                if ((this.RefTurnField.Equals(value) != true)) {
                    this.RefTurnField = value;
                    this.RaisePropertyChanged("RefTurn");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetTurnResultReq", Namespace="http://schemas.datacontract.org/2004/07/Tron.WebService.TransportClasses")]
    [System.SerializableAttribute()]
    public partial class GetTurnResultReq : Tron.DebugClient.ClientService.BaseReq {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PlayerIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlayerId {
            get {
                return this.PlayerIdField;
            }
            set {
                if ((this.PlayerIdField.Equals(value) != true)) {
                    this.PlayerIdField = value;
                    this.RaisePropertyChanged("PlayerId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LeaveGameReq", Namespace="http://schemas.datacontract.org/2004/07/Tron.WebService.TransportClasses")]
    [System.SerializableAttribute()]
    public partial class LeaveGameReq : Tron.DebugClient.ClientService.BaseReq {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PlayerIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlayerId {
            get {
                return this.PlayerIdField;
            }
            set {
                if ((this.PlayerIdField.Equals(value) != true)) {
                    this.PlayerIdField = value;
                    this.RaisePropertyChanged("PlayerId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InitLoginReq", Namespace="http://schemas.datacontract.org/2004/07/Tron.WebService.TransportClasses")]
    [System.SerializableAttribute()]
    public partial class InitLoginReq : Tron.DebugClient.ClientService.BaseReq {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnPoint", Namespace="http://schemas.datacontract.org/2004/07/Tron.WebService.TransportClasses")]
    [System.SerializableAttribute()]
    public partial class EnPoint : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ColField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RowField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Col {
            get {
                return this.ColField;
            }
            set {
                if ((this.ColField.Equals(value) != true)) {
                    this.ColField = value;
                    this.RaisePropertyChanged("Col");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Row {
            get {
                return this.RowField;
            }
            set {
                if ((this.RowField.Equals(value) != true)) {
                    this.RowField = value;
                    this.RaisePropertyChanged("Row");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResp", Namespace="http://schemas.datacontract.org/2004/07/Tron.WebService.TransportClasses")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Tron.DebugClient.ClientService.CompleteLoginResp))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Tron.DebugClient.ClientService.CreatePlayerResp))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Tron.DebugClient.ClientService.WaitGameStartResp))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Tron.DebugClient.ClientService.GetPlayerViewResp))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Tron.DebugClient.ClientService.PerformMoveResp))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Tron.DebugClient.ClientService.WaitNextTurnResp))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Tron.DebugClient.ClientService.GetTurnResultResp))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Tron.DebugClient.ClientService.LeaveGameResp))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Tron.DebugClient.ClientService.InitLoginResp))]
    public partial class BaseResp : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompleteLoginResp", Namespace="http://schemas.datacontract.org/2004/07/Tron.WebService.TransportClasses")]
    [System.SerializableAttribute()]
    public partial class CompleteLoginResp : Tron.DebugClient.ClientService.BaseResp {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SessionIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SessionId {
            get {
                return this.SessionIdField;
            }
            set {
                if ((this.SessionIdField.Equals(value) != true)) {
                    this.SessionIdField = value;
                    this.RaisePropertyChanged("SessionId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreatePlayerResp", Namespace="http://schemas.datacontract.org/2004/07/Tron.WebService.TransportClasses")]
    [System.SerializableAttribute()]
    public partial class CreatePlayerResp : Tron.DebugClient.ClientService.BaseResp {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PlayerIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlayerId {
            get {
                return this.PlayerIdField;
            }
            set {
                if ((this.PlayerIdField.Equals(value) != true)) {
                    this.PlayerIdField = value;
                    this.RaisePropertyChanged("PlayerId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WaitGameStartResp", Namespace="http://schemas.datacontract.org/2004/07/Tron.WebService.TransportClasses")]
    [System.SerializableAttribute()]
    public partial class WaitGameStartResp : Tron.DebugClient.ClientService.BaseResp {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GameIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GameId {
            get {
                return this.GameIdField;
            }
            set {
                if ((this.GameIdField.Equals(value) != true)) {
                    this.GameIdField = value;
                    this.RaisePropertyChanged("GameId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPlayerViewResp", Namespace="http://schemas.datacontract.org/2004/07/Tron.WebService.TransportClasses")]
    [System.SerializableAttribute()]
    public partial class GetPlayerViewResp : Tron.DebugClient.ClientService.BaseResp {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GameStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Tron.DebugClient.ClientService.EnMapData MapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Tron.DebugClient.ClientService.EnPlayerState[] PlayerStatesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TurnField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GameState {
            get {
                return this.GameStateField;
            }
            set {
                if ((object.ReferenceEquals(this.GameStateField, value) != true)) {
                    this.GameStateField = value;
                    this.RaisePropertyChanged("GameState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Index {
            get {
                return this.IndexField;
            }
            set {
                if ((this.IndexField.Equals(value) != true)) {
                    this.IndexField = value;
                    this.RaisePropertyChanged("Index");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Tron.DebugClient.ClientService.EnMapData Map {
            get {
                return this.MapField;
            }
            set {
                if ((object.ReferenceEquals(this.MapField, value) != true)) {
                    this.MapField = value;
                    this.RaisePropertyChanged("Map");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Tron.DebugClient.ClientService.EnPlayerState[] PlayerStates {
            get {
                return this.PlayerStatesField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerStatesField, value) != true)) {
                    this.PlayerStatesField = value;
                    this.RaisePropertyChanged("PlayerStates");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Turn {
            get {
                return this.TurnField;
            }
            set {
                if ((this.TurnField.Equals(value) != true)) {
                    this.TurnField = value;
                    this.RaisePropertyChanged("Turn");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PerformMoveResp", Namespace="http://schemas.datacontract.org/2004/07/Tron.WebService.TransportClasses")]
    [System.SerializableAttribute()]
    public partial class PerformMoveResp : Tron.DebugClient.ClientService.BaseResp {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WaitNextTurnResp", Namespace="http://schemas.datacontract.org/2004/07/Tron.WebService.TransportClasses")]
    [System.SerializableAttribute()]
    public partial class WaitNextTurnResp : Tron.DebugClient.ClientService.BaseResp {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FinishCommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FinishConditionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool GameFinishedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TurnCompleteField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FinishComment {
            get {
                return this.FinishCommentField;
            }
            set {
                if ((object.ReferenceEquals(this.FinishCommentField, value) != true)) {
                    this.FinishCommentField = value;
                    this.RaisePropertyChanged("FinishComment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FinishCondition {
            get {
                return this.FinishConditionField;
            }
            set {
                if ((object.ReferenceEquals(this.FinishConditionField, value) != true)) {
                    this.FinishConditionField = value;
                    this.RaisePropertyChanged("FinishCondition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool GameFinished {
            get {
                return this.GameFinishedField;
            }
            set {
                if ((this.GameFinishedField.Equals(value) != true)) {
                    this.GameFinishedField = value;
                    this.RaisePropertyChanged("GameFinished");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TurnComplete {
            get {
                return this.TurnCompleteField;
            }
            set {
                if ((this.TurnCompleteField.Equals(value) != true)) {
                    this.TurnCompleteField = value;
                    this.RaisePropertyChanged("TurnComplete");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetTurnResultResp", Namespace="http://schemas.datacontract.org/2004/07/Tron.WebService.TransportClasses")]
    [System.SerializableAttribute()]
    public partial class GetTurnResultResp : Tron.DebugClient.ClientService.BaseResp {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GameStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Tron.DebugClient.ClientService.EnPlayerState[] PlayerStatesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TurnField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GameState {
            get {
                return this.GameStateField;
            }
            set {
                if ((object.ReferenceEquals(this.GameStateField, value) != true)) {
                    this.GameStateField = value;
                    this.RaisePropertyChanged("GameState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Tron.DebugClient.ClientService.EnPlayerState[] PlayerStates {
            get {
                return this.PlayerStatesField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerStatesField, value) != true)) {
                    this.PlayerStatesField = value;
                    this.RaisePropertyChanged("PlayerStates");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Turn {
            get {
                return this.TurnField;
            }
            set {
                if ((this.TurnField.Equals(value) != true)) {
                    this.TurnField = value;
                    this.RaisePropertyChanged("Turn");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LeaveGameResp", Namespace="http://schemas.datacontract.org/2004/07/Tron.WebService.TransportClasses")]
    [System.SerializableAttribute()]
    public partial class LeaveGameResp : Tron.DebugClient.ClientService.BaseResp {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InitLoginResp", Namespace="http://schemas.datacontract.org/2004/07/Tron.WebService.TransportClasses")]
    [System.SerializableAttribute()]
    public partial class InitLoginResp : Tron.DebugClient.ClientService.BaseResp {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChallengeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Challenge {
            get {
                return this.ChallengeField;
            }
            set {
                if ((object.ReferenceEquals(this.ChallengeField, value) != true)) {
                    this.ChallengeField = value;
                    this.RaisePropertyChanged("Challenge");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnMapData", Namespace="http://schemas.datacontract.org/2004/07/Tron.WebService.TransportClasses")]
    [System.SerializableAttribute()]
    public partial class EnMapData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] RowsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WidthField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Height {
            get {
                return this.HeightField;
            }
            set {
                if ((this.HeightField.Equals(value) != true)) {
                    this.HeightField = value;
                    this.RaisePropertyChanged("Height");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Rows {
            get {
                return this.RowsField;
            }
            set {
                if ((object.ReferenceEquals(this.RowsField, value) != true)) {
                    this.RowsField = value;
                    this.RaisePropertyChanged("Rows");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Width {
            get {
                return this.WidthField;
            }
            set {
                if ((this.WidthField.Equals(value) != true)) {
                    this.WidthField = value;
                    this.RaisePropertyChanged("Width");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnPlayerState", Namespace="http://schemas.datacontract.org/2004/07/Tron.WebService.TransportClasses")]
    [System.SerializableAttribute()]
    public partial class EnPlayerState : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConditionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Tron.DebugClient.ClientService.EnPoint PositionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Condition {
            get {
                return this.ConditionField;
            }
            set {
                if ((object.ReferenceEquals(this.ConditionField, value) != true)) {
                    this.ConditionField = value;
                    this.RaisePropertyChanged("Condition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Tron.DebugClient.ClientService.EnPoint Position {
            get {
                return this.PositionField;
            }
            set {
                if ((object.ReferenceEquals(this.PositionField, value) != true)) {
                    this.PositionField = value;
                    this.RaisePropertyChanged("Position");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClientService.IClientService")]
    public interface IClientService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/InitLogin", ReplyAction="http://tempuri.org/IClientService/InitLoginResponse")]
        Tron.DebugClient.ClientService.InitLoginResp InitLogin(Tron.DebugClient.ClientService.InitLoginReq req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/InitLogin", ReplyAction="http://tempuri.org/IClientService/InitLoginResponse")]
        System.Threading.Tasks.Task<Tron.DebugClient.ClientService.InitLoginResp> InitLoginAsync(Tron.DebugClient.ClientService.InitLoginReq req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/CompleteLogin", ReplyAction="http://tempuri.org/IClientService/CompleteLoginResponse")]
        Tron.DebugClient.ClientService.CompleteLoginResp CompleteLogin(Tron.DebugClient.ClientService.CompleteLoginReq req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/CompleteLogin", ReplyAction="http://tempuri.org/IClientService/CompleteLoginResponse")]
        System.Threading.Tasks.Task<Tron.DebugClient.ClientService.CompleteLoginResp> CompleteLoginAsync(Tron.DebugClient.ClientService.CompleteLoginReq req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/CreatePlayer", ReplyAction="http://tempuri.org/IClientService/CreatePlayerResponse")]
        Tron.DebugClient.ClientService.CreatePlayerResp CreatePlayer(Tron.DebugClient.ClientService.CreatePlayerReq req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/CreatePlayer", ReplyAction="http://tempuri.org/IClientService/CreatePlayerResponse")]
        System.Threading.Tasks.Task<Tron.DebugClient.ClientService.CreatePlayerResp> CreatePlayerAsync(Tron.DebugClient.ClientService.CreatePlayerReq req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/WaitGameStart", ReplyAction="http://tempuri.org/IClientService/WaitGameStartResponse")]
        Tron.DebugClient.ClientService.WaitGameStartResp WaitGameStart(Tron.DebugClient.ClientService.WaitGameStartReq req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/WaitGameStart", ReplyAction="http://tempuri.org/IClientService/WaitGameStartResponse")]
        System.Threading.Tasks.Task<Tron.DebugClient.ClientService.WaitGameStartResp> WaitGameStartAsync(Tron.DebugClient.ClientService.WaitGameStartReq req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/GetPlayerView", ReplyAction="http://tempuri.org/IClientService/GetPlayerViewResponse")]
        Tron.DebugClient.ClientService.GetPlayerViewResp GetPlayerView(Tron.DebugClient.ClientService.GetPlayerViewReq req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/GetPlayerView", ReplyAction="http://tempuri.org/IClientService/GetPlayerViewResponse")]
        System.Threading.Tasks.Task<Tron.DebugClient.ClientService.GetPlayerViewResp> GetPlayerViewAsync(Tron.DebugClient.ClientService.GetPlayerViewReq req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/PerformMove", ReplyAction="http://tempuri.org/IClientService/PerformMoveResponse")]
        Tron.DebugClient.ClientService.PerformMoveResp PerformMove(Tron.DebugClient.ClientService.PerformMoveReq req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/PerformMove", ReplyAction="http://tempuri.org/IClientService/PerformMoveResponse")]
        System.Threading.Tasks.Task<Tron.DebugClient.ClientService.PerformMoveResp> PerformMoveAsync(Tron.DebugClient.ClientService.PerformMoveReq req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/WaitNextTurn", ReplyAction="http://tempuri.org/IClientService/WaitNextTurnResponse")]
        Tron.DebugClient.ClientService.WaitNextTurnResp WaitNextTurn(Tron.DebugClient.ClientService.WaitNextTurnReq req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/WaitNextTurn", ReplyAction="http://tempuri.org/IClientService/WaitNextTurnResponse")]
        System.Threading.Tasks.Task<Tron.DebugClient.ClientService.WaitNextTurnResp> WaitNextTurnAsync(Tron.DebugClient.ClientService.WaitNextTurnReq req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/GetTurnResult", ReplyAction="http://tempuri.org/IClientService/GetTurnResultResponse")]
        Tron.DebugClient.ClientService.GetTurnResultResp GetTurnResult(Tron.DebugClient.ClientService.GetTurnResultReq req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/GetTurnResult", ReplyAction="http://tempuri.org/IClientService/GetTurnResultResponse")]
        System.Threading.Tasks.Task<Tron.DebugClient.ClientService.GetTurnResultResp> GetTurnResultAsync(Tron.DebugClient.ClientService.GetTurnResultReq req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/LeaveGame", ReplyAction="http://tempuri.org/IClientService/LeaveGameResponse")]
        Tron.DebugClient.ClientService.LeaveGameResp LeaveGame(Tron.DebugClient.ClientService.LeaveGameReq req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/LeaveGame", ReplyAction="http://tempuri.org/IClientService/LeaveGameResponse")]
        System.Threading.Tasks.Task<Tron.DebugClient.ClientService.LeaveGameResp> LeaveGameAsync(Tron.DebugClient.ClientService.LeaveGameReq req);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClientServiceChannel : Tron.DebugClient.ClientService.IClientService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientServiceClient : System.ServiceModel.ClientBase<Tron.DebugClient.ClientService.IClientService>, Tron.DebugClient.ClientService.IClientService {
        
        public ClientServiceClient() {
        }
        
        public ClientServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClientServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Tron.DebugClient.ClientService.InitLoginResp InitLogin(Tron.DebugClient.ClientService.InitLoginReq req) {
            return base.Channel.InitLogin(req);
        }
        
        public System.Threading.Tasks.Task<Tron.DebugClient.ClientService.InitLoginResp> InitLoginAsync(Tron.DebugClient.ClientService.InitLoginReq req) {
            return base.Channel.InitLoginAsync(req);
        }
        
        public Tron.DebugClient.ClientService.CompleteLoginResp CompleteLogin(Tron.DebugClient.ClientService.CompleteLoginReq req) {
            return base.Channel.CompleteLogin(req);
        }
        
        public System.Threading.Tasks.Task<Tron.DebugClient.ClientService.CompleteLoginResp> CompleteLoginAsync(Tron.DebugClient.ClientService.CompleteLoginReq req) {
            return base.Channel.CompleteLoginAsync(req);
        }
        
        public Tron.DebugClient.ClientService.CreatePlayerResp CreatePlayer(Tron.DebugClient.ClientService.CreatePlayerReq req) {
            return base.Channel.CreatePlayer(req);
        }
        
        public System.Threading.Tasks.Task<Tron.DebugClient.ClientService.CreatePlayerResp> CreatePlayerAsync(Tron.DebugClient.ClientService.CreatePlayerReq req) {
            return base.Channel.CreatePlayerAsync(req);
        }
        
        public Tron.DebugClient.ClientService.WaitGameStartResp WaitGameStart(Tron.DebugClient.ClientService.WaitGameStartReq req) {
            return base.Channel.WaitGameStart(req);
        }
        
        public System.Threading.Tasks.Task<Tron.DebugClient.ClientService.WaitGameStartResp> WaitGameStartAsync(Tron.DebugClient.ClientService.WaitGameStartReq req) {
            return base.Channel.WaitGameStartAsync(req);
        }
        
        public Tron.DebugClient.ClientService.GetPlayerViewResp GetPlayerView(Tron.DebugClient.ClientService.GetPlayerViewReq req) {
            return base.Channel.GetPlayerView(req);
        }
        
        public System.Threading.Tasks.Task<Tron.DebugClient.ClientService.GetPlayerViewResp> GetPlayerViewAsync(Tron.DebugClient.ClientService.GetPlayerViewReq req) {
            return base.Channel.GetPlayerViewAsync(req);
        }
        
        public Tron.DebugClient.ClientService.PerformMoveResp PerformMove(Tron.DebugClient.ClientService.PerformMoveReq req) {
            return base.Channel.PerformMove(req);
        }
        
        public System.Threading.Tasks.Task<Tron.DebugClient.ClientService.PerformMoveResp> PerformMoveAsync(Tron.DebugClient.ClientService.PerformMoveReq req) {
            return base.Channel.PerformMoveAsync(req);
        }
        
        public Tron.DebugClient.ClientService.WaitNextTurnResp WaitNextTurn(Tron.DebugClient.ClientService.WaitNextTurnReq req) {
            return base.Channel.WaitNextTurn(req);
        }
        
        public System.Threading.Tasks.Task<Tron.DebugClient.ClientService.WaitNextTurnResp> WaitNextTurnAsync(Tron.DebugClient.ClientService.WaitNextTurnReq req) {
            return base.Channel.WaitNextTurnAsync(req);
        }
        
        public Tron.DebugClient.ClientService.GetTurnResultResp GetTurnResult(Tron.DebugClient.ClientService.GetTurnResultReq req) {
            return base.Channel.GetTurnResult(req);
        }
        
        public System.Threading.Tasks.Task<Tron.DebugClient.ClientService.GetTurnResultResp> GetTurnResultAsync(Tron.DebugClient.ClientService.GetTurnResultReq req) {
            return base.Channel.GetTurnResultAsync(req);
        }
        
        public Tron.DebugClient.ClientService.LeaveGameResp LeaveGame(Tron.DebugClient.ClientService.LeaveGameReq req) {
            return base.Channel.LeaveGame(req);
        }
        
        public System.Threading.Tasks.Task<Tron.DebugClient.ClientService.LeaveGameResp> LeaveGameAsync(Tron.DebugClient.ClientService.LeaveGameReq req) {
            return base.Channel.LeaveGameAsync(req);
        }
    }
}
